env: local

server:
  port: 8081

sandbox:
  work_dir: /sandbox
  host: unix:///var/run/docker.sock
  rules:
    python:
      filename: main.py
      image: python
      launch: cat input.txt | python3 main.py
