server:
  env: dev
  address: :8081

sandbox:
  user: sandbox
  uuid: 3456
  work_dir: /sandbox
  host: unix:///var/run/docker.sock
  rules:
    "python":
      filename: main.py
      image: python-coderunner:latest
      launch: python3