env: dev

server:
  port: 8081

sandbox:
  user: root
  uuid: 0
  work_dir: /sandbox
  host: unix:///var/run/docker.sock
  rules:
    python:
      filename: main.py
      image: python
      launch: python3
