env: local

server:
  address: :8081

sandbox:
  user: sandbox
  uuid: 3456
  work_dir: /sandbox
  host: unix:///var/run/docker.sock
  rules:
    "python":
      filename: main.py
      image: python-coderunner:3.12.3
      launch: cat input.txt | python3 main.py

